services:
  influxdb:
    image: influxdb:1.8-alpine
    container_name: k6_influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=k6
    networks:
      - k6
      - grafana
      - influxdb

  grafana:
    image: grafana/grafana-oss:8.2.6
    container_name: k6_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    depends_on:
      - influxdb
    networks:
      - grafana
      - influxdb

  k6:
    image: grafana/k6:latest
    container_name: k6_runner
    networks:
      - k6
    environment:
      - API_PASS=${API_PASS}
      - BASE_URL=${BASE_URL:-https://app-getpay-prod-3-staging.azurewebsites.net}
      - API_USER=${API_USER:-c50afe5f-0175-4480-9bc1-5a919e339fe3}
    volumes:
      - ../tests/k6:/scripts
    command: run --out influxdb=http://influxdb:8086/k6 /scripts/load-test-payin.js
    depends_on:
      - influxdb

networks:
  k6:
  grafana:
  influxdb:

volumes:
  influxdb_data:
    driver: local
  grafana_data:
    driver: local