apiVersion: 1

datasources:
  - name: InfluxDB_K6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    isDefault: true
    jsonData:
      httpMode: GET
    editable: true