name: Deploy PHP App to Azure Web App/staging

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Clonar o repositório
    - name: Checkout code
      uses: actions/checkout@v4

    # Passo 2: Configurar o ambiente PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, json, curl, dom, fileinfo, pdo, pdo_mysql # Adicione extensões PHP necessárias
        tools: composer

    # Passo 3: Instalar dependências do Composer
    # Isso criará a pasta 'vendor' com as bibliotecas do PHP
    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    # Passo 4: Configurar o ambiente Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Use a versão do Node.js que seu projeto requer
        cache: 'npm' # Habilita o cache para as dependências do npm

    # Passo 5: Instalar dependências do NPM
    - name: Install NPM dependencies
      run: npm install

    # Passo 6: Compilar os assets (CSS/JS)
    # Isso executará o script 'build' do seu package.json
    - name: Build with NPM
      run: npm run build

    # Passo 7: Fazer o deploy para o Azure Web App
    # Este passo enviará todos os arquivos, incluindo a pasta 'vendor' e os assets compilados
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-getpay'
        slot-name: 'staging'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_58CEDE20349640D6921683CEBAC3DEFB }}
        package: . # Garante que o diretório atual seja empacotado e enviado